/**
 * Export helpers — Markdown + CSV serialisation and browser download.
 */

import type { ExportFormat, Question } from './types';

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function escapeCsv(s: string): string {
  // RFC 4180: wrap in double quotes, escape internal quotes.
  return '"' + s.replace(/"/g, '""') + '"';
}

export function toMarkdown(questions: Question[]): string {
  const lines: string[] = [];
  lines.push(`# Quiz`);
  lines.push('');
  lines.push(`> Generated by Free PDF to Quiz. ${questions.length} question${questions.length === 1 ? '' : 's'}.`);
  lines.push('');

  for (const q of questions) {
    lines.push(`## Question ${q.id}`);
    lines.push('');
    lines.push(`**${q.prompt}**`);
    lines.push('');
    const letters = ['A', 'B', 'C', 'D'] as const;
    q.options.forEach((opt, i) => {
      const marker = i === q.correctIndex ? ' (correct)' : '';
      lines.push(`- ${letters[i]}. ${opt}${marker}`);
    });
    lines.push('');
    lines.push(`*Explanation:* ${q.explanation}`);
    lines.push('');
    lines.push(`*Source:* ${q.sourceSentence}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

export function toCSV(questions: Question[]): string {
  const header = [
    'id',
    'difficulty',
    'prompt',
    'option_a',
    'option_b',
    'option_c',
    'option_d',
    'correct_index',
    'correct_letter',
    'explanation',
    'source_sentence',
  ];
  const rows = [header.join(',')];
  for (const q of questions) {
    rows.push(
      [
        q.id,
        q.difficulty,
        escapeCsv(q.prompt),
        escapeCsv(q.options[0]),
        escapeCsv(q.options[1]),
        escapeCsv(q.options[2]),
        escapeCsv(q.options[3]),
        q.correctIndex,
        ['A', 'B', 'C', 'D'][q.correctIndex],
        escapeCsv(q.explanation),
        escapeCsv(q.sourceSentence),
      ].join(',')
    );
  }
  return rows.join('\n');
}

function triggerDownload(filename: string, mime: string, body: string) {
  const blob = new Blob([body], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 0);
}

export function downloadAs(questions: Question[], format: ExportFormat) {
  const stamp = new Date().toISOString().slice(0, 10);
  if (format === 'md') {
    triggerDownload(`quiz-${stamp}.md`, 'text/markdown;charset=utf-8', toMarkdown(questions));
  } else {
    triggerDownload(`quiz-${stamp}.csv`, 'text/csv;charset=utf-8', toCSV(questions));
  }
}

export async function copyAsMarkdown(questions: Question[]): Promise<boolean> {
  const text = toMarkdown(questions);
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // fall through
  }
  // Fallback: select + execCommand
  try {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}
